### ISSUE TITLE
Add merge sort

### ISSUE THREAD

**Issue by Fancy-angel** [1dharode/Hacktoberfest2021#221]
This file should contain merge sort in c

**Comment by maleeshasilva** [comment]
can I work on this?

**Comment by umak1106** [comment]
I added mergesort in c . My pr is 246.

**Comment by HimanshiGupta010** [comment]
Hello,
I want to contribute as a contributer as a Hacktoberfest2021, So please assign this issue to me.

**Comment by prachi996** [comment]
hey, please assign this to me

**Comment by Khushi-Mattu** [comment]
I want to work on this issue. do assign it to me
